#ifndef __NET_CONSTANTS__
typedef enum
{
	NET_ERROR_PACKET=0,
	NET_STATUS_PACKET=1,
	NET_MESSAGE_PACKET=2,
	NET_COMMAND_PACKET=3,
	NET_COLOUR_PACKET=4,
	NET_ULTRASONIC_PACKET=5
} TNetConstants;

#endif
